# Generated by Django 5.2.1 on 2025-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(help_text='Name of the car being launched.', max_length=200)),
                ('car_minimal_details', models.TextField(blank=True, help_text='e.g., Engine CC, Power (BHP), Torque (Nm), Transmission type.')),
                ('car_description', models.TextField(blank=True, help_text='Detailed description of the upcoming car.')),
                ('image', models.ImageField(blank=True, help_text='Image of the upcoming car.', null=True, upload_to='upcoming_launches/')),
                ('launch_date', models.DateField(help_text='Date of the car launch event.')),
                ('launch_time_start', models.TimeField(help_text='Start time of the launch event.')),
                ('launch_time_end', models.TimeField(help_text='End time of the launch event.')),
                ('venue', models.CharField(help_text="Name of the launch venue (e.g., 'Exhibition Hall 3').", max_length=255)),
                ('location', models.CharField(help_text="City and state/country of the launch event (e.g., 'Mumbai, India').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upcoming Launch',
                'verbose_name_plural': 'Upcoming Launches',
                'ordering': ['launch_date', 'launch_time_start'],
            },
        ),
    ]
