# Generated by Django 5.1.1 on 2025-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('ZIBER', 'ZIBER'), ('Toyota', 'Toyota'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('is_new', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
