# Generated by Django 5.1.1 on 2025-04-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=-2008, max_length=50),
            preserve_default=False,
        ),
    ]
