# Generated by Django 5.1.5 on 2025-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
