# Generated by Django 5.1.5 on 2025-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_jobvacancy_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='car_model',
            field=models.CharField(choices=[('Model X1', 'Model X1'), ('Model X2', 'Model X2'), ('Model Y1', 'Model Y1'), ('Model Y2', 'Model Y2')], max_length=100),
        ),
    ]
