# Generated by Django 5.2.1 on 2025-05-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_servicebooking_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='car_model',
            field=models.CharField(max_length=100),
        ),
    ]
